<a href="https://colab.research.google.com/github/Russy-Veemon/Classification-with-a-Tabular-Vector-Borne-Disease-Dataset/blob/main/Russy_Vee_KagglePracticeComp_Classification_with_a_Tabular_Vector_Borne_Disease_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import csv

In [8]:
with open('sample_submission.csv', 'r') as fp:
  print(fp)

<_io.TextIOWrapper name='sample_submission.csv' mode='r' encoding='UTF-8'>


In [9]:
with open('sample_submission.csv', 'r') as fp:
  for index, line in enumerate(fp.readlines()):
    if (index < 10):
      print(index, line)

0 id,prognosis

1 707,Dengue Zika Japanese_encephalitis

2 708,Dengue Zika Japanese_encephalitis

3 709,Dengue Zika Japanese_encephalitis

4 710,Dengue Zika Japanese_encephalitis

5 711,Dengue Zika Japanese_encephalitis

6 712,Dengue Zika Japanese_encephalitis

7 713,Dengue Zika Japanese_encephalitis

8 714,Dengue Zika Japanese_encephalitis

9 715,Dengue Zika Japanese_encephalitis



In [11]:
with open ('sample_submission.csv', 'r') as fp:
  reader = csv.reader(fp, delimiter=',')
  next(reader)
  for index, values in enumerate (reader):
    id, prognosis = values
    print(f"{id} has this {prognosis}")

NameError: ignored

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [1]:
train["null_count"] = train.isnull().sum(axis=1)
counts = train.groupby("null_count")["id"].count().to_dict()
null_data = {"{} Null Value(s)".format(k) : v for k, v in counts.items() if k < 8}

fig, axs = plt.subplots(nrows=1, ncols=2, figsize=(10, 7))

axs = axs.flatten()

_ = axs[0].pie(
    x=list(null_data.values()), 
    autopct=lambda x: "{:,.0f} = {:.2f}%".format(x * sum(null_data.values())/100, x),
    explode=[0.05] * len(null_data.keys()), 
    labels=null_data.keys(), 
    colors=sns.color_palette("Set2")[0:3],
)
_ = axs[0].set_title("Number of Null Values Per Row (Train)", fontsize=15)

test["null_count"] = test.isnull().sum(axis=1)
counts = test.groupby("null_count")["id"].count().to_dict()
null_data = {"{} Null Value(s)".format(k) : v for k, v in counts.items() if k < 8}

_ = axs[1].pie(
    x=list(null_data.values()), 
    autopct=lambda x: "{:,.0f} = {:.2f}%".format(x * sum(null_data.values())/100, x),
    explode=[0.05] * len(null_data.keys()), 
    labels=null_data.keys(), 
    colors=sns.color_palette("Set1")[0:3],
)
_ = axs[1].set_title("Number of Null Values Per Row (Test)", fontsize=15)

train = train.drop("null_count", axis=1)
test = test.drop("null_count", axis=1)


NameError: ignored

In [7]:
import numpy as np

a = np.array(([1, 2, 3, 4, 5], [6, 7, 8, 9, 10]))
b = np.max(a, axis=0).sum()
print(a)
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[ 6  7  8  9 10]
